### ISSUE TITLE
Composer?

### ISSUE THREAD

**Issue by spekulatius** [ins0/github-changelog-generator#1]
Could you add a composer.json file and list the package on packagist? That would be great! :)

**Comment by ins0** [comment]
Dang, @spekulatius totaly forget about this one :sob: - will add this package to composer today! Sry man!

**Comment by spekulatius** [comment]
No worries. All good. Just noticed it and thought it would be great to have a composer file.

**Comment by ins0** [comment]
@spekulatius sry for the long time, composer is now set up. Thank you!
